---

- name: Create user group
  group: name="{{ item.username }}" gid="{{  item.uid | default(omit) }}"
  with_items: "{{ users }}"

- name: Create app user
  user: name="{{ item.username }}"
        groups="{{ item.groups | default([]) | join(',') }}"
        shell={{ item.shell if item.shell is defined else users_default_shell }}
        comment="{{ item.description }}"
        uid="{{ item.uid | default(omit) }}"
        home="{{ item.home | default(omit) }}"
        state=present
        force=yes
  with_items: "{{ users }}"
